'use strict';

// 初始化图表
export const CHART_INVALIDATE = 'CHART_INVALIDATE';
export const CHART_REQUEST = 'CHART_REQUEST';
export const CHART_SUCCESS = 'CHART_SUCCESS';
export const CHART_FAILURE = 'CHART_FAILURE';

// 过滤图表
export const FILTER_CHART_REQUEST = 'FILTER_CHART_REQUEST';
export const FILTER_CHART_SUCCESS = 'FILTER_CHART_SUCCESS';
export const FILTER_CHART_FAILURE = 'FILTER_CHART_FAILURE';

// 改变图表类型
export const CHANGE_CHART_REQUEST = 'CHANGE_CHART_REQUEST';
export const CHANGE_CHART_SUCCESS = 'CHANGE_CHART_SUCCESS';
export const CHANGE_CHART_FAILURE = 'CHANGE_CHART_FAILURE';
