'use strict';

// 获取用户
export const CLIENT_REQUEST = 'CLIENT_REQUEST';
export const CLIENT_SUCCESS = 'CLIENT_SUCCESS';
export const CLIENT_FAILURE = 'CLIENT_FAILURE';

// 用户详情
export const DETAIL_CLIENT_REQUEST = 'DETAIL_CLIENT_REQUEST';
export const DETAIL_CLIENT_SUCCESS = 'DETAIL_CLIENT_SUCCESS';
export const DETAIL_CLIENT_FAILURE = 'DETAIL_CLIENT_FAILURE';

// 重置密码
export const RESET_PWD_REQUEST = 'RESET_PWD_REQUEST';
export const RESET_PWD_SUCCESS = 'RESET_PWD_SUCCESS';
export const RESET_PWD_FAILURE = 'RESET_PWD_FAILURE';

// 重置两部验证
export const RESET_AUTH_REQUEST = 'RESET_AUTH_REQUEST';
export const RESET_AUTH_SUCCESS = 'RESET_AUTH_SUCCESS';
export const RESET_AUTH_FAILURE = 'RESET_AUTH_FAILURE';

// 暂停用户
export const PAUSE_REQUEST = 'PAUSE_REQUEST';
export const PAUSE_SUCCESS = 'PAUSE_SUCCESS';
export const PAUSE_FAILURE = 'PAUSE_FAULURE';

// 删除用户
export const DEL_REQUEST = 'DEL_REQUEST';
export const DEL_SUCCESS = 'DEL_SUCCESS';
export const DEL_FAILURE = 'DEL_FAILURE';

// 增加临时配额
export const ADD_QUATO_REQUEST = 'ADD_QUATO_REQUEST';
export const ADD_QUATO_SUCCESS = 'ADD_QUATO_SUCCESS';
export const ADD_QUATO_FAILURE = 'ADD_QUATO_FAILURE';

// 导出日志
export const EXPORT_LOG_REQUEST = 'EXPORT_LOG_REQUEST';
export const EXPORT_LOG_SUCCESS = 'EXPORT_LOG_SUCCESS';
export const EXPORT_LOG_FAILURE = 'EXPORT_LOG_FAILURE';

// 添加成员
export const ADD_REQUEST = 'ADD_REQUEST';
export const ADD_SUCCESS = 'ADD_SUCCESS';
export const ADD_FAILURE = 'ADD_FAILURE';

// 移出群组
export const OFF_GROUP_REQUEST = 'OFF_GROUP_REQUEST';
export const OFF_GROUP_SUCCESS = 'OFF_GROUP_SUCCESS';
export const OFF_GROUP_FAILURE = 'OFF_GROUP_FAILURE';

// 删除设备
export const DEL_DEVICE_REQUEST = 'DEL_DEVICE_REQUEST';
export const DEL_DEVICE_SUCCESS = 'DEL_DEVICE_SUCCESS';
export const DEL_DEVICE_FAILURE = 'DEL_DEVICE_FAILURE';
