'use strict';

// 获取群组列表
export const GROUP_REQUEST = 'GROUP_REQUEST';
export const GROUP_SUCCESS = 'GROUP_SUCCESS';
export const GROUP_FAILURE = 'GROUP_FAILURE';

// 获取单个群组详情
export const DETAIL_GROUP_REQUEST = 'DETAIL_GROUP_REQUEST';
export const DETAIL_GROUP_SUCCESS = 'DETAIL_GROUP_SUCCESS';
export const DETAIL_GROUP_FAILURE = 'DETAIL_GROUP_FAILURE';

// 编辑群组名
export const EDIT_GROUPNAME_REQUEST = 'EDIT_GROUPNAME_REQUEST';
export const EDIT_GROUPNAME_SUCCESS = 'EDIT_GROUPNAME_SUCCESS';
export const EDIT_GROUPNAME_FAILURE = 'EDIT_GROUPNAME_FAILURE';
