'use strict';

// 更改套餐
export const EDIT_PACKAGE_REQUEST = 'EDIT_PACKAGE_REQUEST';
export const EDIT_PACKAGE_SUCCESS = 'EDIT_PACKAGE_SUCCESS';
export const EDIT_PACKAGE_FAILURE = 'EDIT_PACKAGE_FAILURE';

// 流量阈值告警
export const THRESHOLD_REQUEST = 'THRESHOLD_REQUEST';
export const THRESHOLD_SUCCESS = 'THRESHOLD_SUCCESS';
export const THRESHOLD_FAILURE = 'THRESHOLD_FAILURE';

// 支付
export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILURE = 'PAYMENT_FAILURE'; 
