'use strict';

// 语言设置
export const LA_SETTING_REQUEST = 'CHANGE_LA_REQUEST';
export const LA_SETTING_SUCCESS = 'CHANGE_LA_SUCCESS';
export const LA_SETTING_FAILURE = 'CHANGE_LA_FAILURE';

// 两步认证
export const AUTH_SETTING_REQUEST = 'AUTH_SETTING_REQUEST';
export const AUTH_SETTING_SUCCESS = 'AUTH_SETTING_SUCCESS';
export const AUTH_SETTING_FAILURE = 'AUTH_SETTING_FAILURE';

// 单点登录
export const SSO_SETTING_REQUEST = 'SSO_SETTING_REQUEST';
export const SSO_SETTING_SUCCESS = 'SSO_SETTING_SUCCESS';
export const SSO_SETTING_FAILURE = 'SSO_SETTING_FAILURE';

// 登录设备认证
export const DEVICE_SETTING_REQUEST = 'DEVICE_SETTING_REQUEST';
export const DEVICE_SETTING_SUCCESS = 'DEVICE_SETTING_SUCCESS';
export const DEVICE_SETTING_FAILURE = 'DEVICE_SETTING_FAILURE';

// 重置密码
export const RESET_PWD_SETTING_REQUEST = 'RESET_PWD_SETTING_REQUEST';
export const RESET_PWD_SETTING_SUCCESS = 'RESET_PWD_SETTING_SUCCESS';
export const RESET_PWD_SETTING_FAILURE = 'RESET_PWD_SETTING_SUCCESS';

// 立刻重置全部人员密码
export const RESET_PWD_ALL_REQUEST = 'RESET_PWD_ALL_REQUEST';
export const RESET_PWD_ALL_SUCCESS = 'RESET_PWD_ALL_SUCCESS';
export const RESET_PWD_ALL_FAILURE = 'RESET_PWD_ALL_FAILURE';

// 客户端聊天
export const CHAT_SETTING_REQUEST = 'CHAT_SETTING_REQUEST';
export const CHAT_SETTING_SUCCESS = 'CHAT_SETTING_SUCCESS';
export const CHAT_SETTING_FAILURE = 'CHAT_SETTING_FAILURE';
