'use strict';

// 流量统计下文件详情
export const TRAFFIC_FILE_REQUEST = 'TRAFFIC_FILE_REQUEST';
export const TRAFFIC_FILE_SUCCESS = 'TRAFFIC_FILE_SUCCESS';
export const TRAFFIC_FILE_FAILURE = 'TRAFFIC_FILE_FAILURE';

// 流量统计下个人流量配置
export const EDIT_QUOTA_REQUEST = 'EDIT_QUOTA_REQUEST';
export const EDIT_QUOTA_SUCCESS = 'EDIT_QUOTA_SUCCESS';
export const EDIT_QUOTA_FAILURE = 'EDIT_QUOTA_FAILURE';
